### ISSUE TITLE
R4i Upgrade v 1.4 (www.r4-v.com)

### ISSUE THREAD

**Issue by zacchi4k** [ntrteam/flashcart_core#115]
I've used the new [rewritten NDS Ntrboot flasher](https://github.com/jason0597/ntrboot_flasher_nds/releases) on my DS Lite.
The card gets recognized as part of the R4iSDHC family, but when I try to flash the FIRM (I use the [Boot9strap_ntr.firm](https://github.com/SciresM/boot9strap/releases/download/1.3/boot9strap-1.3-ntr.zip))  it returns a "Failed to inject FIRM!" error.

[Here's the debug.log](https://1drv.ms/u/s!Aqe0WlOd9Hksxgluo0c1LzSKYphb) from the flashcart's microSD card, [here's the dump](https://1drv.ms/u/s!Aqe0WlOd9HksxgxP3jJZYLBA-9pJ) I got from the "Dump flash" option and [here's the kernel](https://www.linfoxdomain.com/nintendo/ds/dl.php/R4v_R4i_v2.2_English.rar) for this flashcart.

<details><summary>Images <em>(Click to Expand)</em></summary><p> 

![Label](https://s19.postimg.org/daqypjbcz/P_20171209_162346.jpg)
![PCB Front](https://s19.postimg.org/xi4ehuo9v/P_20171209_162414.jpg)
![PCB Back](https://s19.postimg.org/q254w2g03/P_20171209_162420.jpg)
![NDS](https://s19.postimg.org/qrnx8f8tv/P_20171209_162854.jpg)
!!NOTE!!: The flashcart can't actually be used in a 3DS since it's blocked. I put it in my 3DS only because my DS Lite sometimes takes a lot of tries to read a card.

</p></details>

**Comment by ShadixAced** [comment]
For me, seems like a pure clone of R4i-SDHC cards yep, but something in this cart looks weird to me...

**Comment by zacchi4k** [comment]
@ShadixAced if it's a clone, then why can't the ntr flasher inject the FIRM?

**Comment by ShadixAced** [comment]
Maybe because the chip does not recognise them, or might have been changed by the R4-V team, which looks weird to me.

**Comment by ShadixAced** [comment]
Or maybe it's a NOR problem ? You haven't done a GM9 / D9 flash dump though

**Comment by zacchi4k** [comment]
@ShadixAced  I can't, I don't have a modded 3DS. But I did do a dump via the dump option in the new NDS ntrboot flasher

**Comment by ShadixAced** [comment]
Oh yes my bad. Did you try DSTT ?

**Comment by zacchi4k** [comment]
@ShadixAced  it only recognizes it as a R4 SDHC

**Comment by ShadixAced** [comment]
Okay. That's weird considering that he was recognized. Do not know if the NDS file work correctly. The flash might protect himself from flashing or might be a read issue.

**Comment by zacchi4k** [comment]
@ShadixAced  I also posted the log file

**Comment by ShadixAced** [comment]
Saw it, it is a NOR issue, that it does not end or start by FF.

**Comment by jason0597** [comment]
@ShadixAced I did try my best to make it so that there is minimal interference from other factors like kernel, sd init, fat mount etc. However I cannot guarantee that having the kernel run and do it’s thing before running the nds flasher, won’t affect it at all

**Comment by ShadixAced** [comment]
@jason0597 At least I've saw you did a great work, but yep, might be one part of your code that might have interfered with @zacchi4k 's flashcart. 

@zacchi4k Try to dump your cart, and @jason0597 if you know a lot about flashcart updater or how the NOR works, well will be a good source.

**Comment by jason0597** [comment]
unfortunately i'm not that experienced with how the r4isdhc works

**Comment by dark-samus** [comment]
This looks very much like a DSTT clone. Run the DSTT option and send us the
log please

**Comment by dark-samus** [comment]
Also, can you get us the numbers on the chip? It appears they burned some of them off, but something might end up being useful

**Comment by zacchi4k** [comment]
@ShadixAced 
I did already dump my flashcart with the dump option in the flasher, but now I also did [a dump](https://1drv.ms/u/s!Aqe0WlOd9Hksxg0uA5RH25CiHBr2) with [dsflashcartdump](https://github.com/angelsl/dsflashcartdump/releases/download/v0.0.0/dsflashcartdump.nds)
@dark-samus [here's the log](https://1drv.ms/u/s!Aqe0WlOd9Hksxg6SHcy-tITNSqsZ). 

Also, here are the label on the chips:
![Back labeled](https://s19.postimg.org/ppg321uk3/back_labeled.jpg)
![Front labeled](https://s19.postimg.org/claipda83/front_labeled.jpg)

I put a black rectangle where they put something on the chip, although it LOOKS like there wasn't actually anything written below

**!NOTE!** I did use a DSi for this, since my DS Lite doesn't want to read this flashcart anymore for some reason

**Comment by dark-samus** [comment]
Indeed, this seems to be a DSTT clone. It gets what appears to be a valid flash chip ID, but likely we just don't support that flashchip currently

**Comment by zacchi4k** [comment]
@dark-samus Also, I followed this guide to install YSMenu, and indeed, this cart needs the "DSTTi-Clone" folder, so yeah...
How hard would it be to add support?

**Comment by dark-samus** [comment]
Well, first things first, we needed to know what flashchip it is. The text you provided from the big chip gave me that. Punching some of the text into Google got me a datasheet, which in turn gives me the flash commands. From there it's figuring a few things out. Block size, chip ID (which you provided with the log), among some other things. After that it's just doing the work of integrating it into the DSTT code

**Comment by dark-samus** [comment]
Also; lol, the dump from dsflashcart dump is literally all zeros...

**Comment by zacchi4k** [comment]
@dark-samus is there some way I could you with the other things needed to know?

**Comment by dark-samus** [comment]
@zacchi4k just try this build for me. This one will only read the flash, it won't restore or inject ntrboot

**Comment by jason0597** [comment]
@dark-samus i don't think they have a hacked 3ds

**Comment by zacchi4k** [comment]
@dark-samus I don't have a modded 3DS, so I can only use .nds flashers. Sorry :/

**Comment by dark-samus** [comment]
ah, well, I can compile a DS version :)

**Comment by dark-samus** [comment]
@jason0597 trying to compile your version I'm getting an error, which makes perfect sense, I'm just not sure how it made it to git or if I'm missing something here...

ntrboot_flasher_nds/source/menu.cpp:122:4: error: 'breakCondition' was not declared in this scope
    breakCondition = true;

**Comment by dark-samus** [comment]
@zacchi4k whenever you're ready... Do NOT attempt to restore the flash or inject ntrboot yet, this should *just* read flash.

[ntrboot_flasher_nds.zip](https://github.com/ntrteam/flashcart_core/files/1557358/ntrboot_flasher_nds.zip)

**Comment by jason0597** [comment]
@dark-samus ah yes that was a bad commit, i'll fix it now

**Comment by dark-samus** [comment]
@jason0597 I usually run all my commits through a "make" before pushing to git, catches a lot of silly mistakes ;)

**Comment by jason0597** [comment]
@dark-samus how did you get your binary to be so small? it's 50kb smaller than the one i make

**Comment by dark-samus** [comment]
@jason0597 possibly using an outdated version of dkP

**Comment by zacchi4k** [comment]
@dark-samus It still says flashcart setup failed, [Here's the log](https://1drv.ms/u/s!Aqe0WlOd9HksxhFCMPmTg5Xorzvk)
Could it be that the chip ID changes every time you boot the card??

**Comment by dark-samus** [comment]
@zacchi4k yeah, it probably is a DSTTi rather than just a DSTT... Might need different code to support it tbh.

**Comment by zacchi4k** [comment]
So support shouldn't be excepted anytime soon? What about a separate flasher designed for this cart (or all DSTTi and clones?) which ignores the chip ID?

**Comment by dark-samus** [comment]
Well, likely the chip ID will still be important, it might just be that we
need secure init or something.

**Comment by zacchi4k** [comment]
I managed to mod my 3DS with another flashcart, and I was able to dump the cart with both twopassdump and GM9

Here's the [twopassdump dump](https://1drv.ms/u/s!Aqe0WlOd9HksxiY_vVvDSyh4mkFx) (the dumper shows raw_chipid: FC2 even when dumping the cart multiple times), and here's the [GM9 dump](https://1drv.ms/u/s!Aqe0WlOd9Hksxidhs_NCbd5fPUxy)

**Comment by cutecodee** [comment]
is there any chance to get the R4i V1.4 working?
